services:
    _defaults:
        autoconfigure: true
        autowire: true

    pix_sortable_behavior.position.orm:
        class: Pix\SortableBehaviorBundle\Services\PositionORMHandler
        public: false
        arguments:
            - "@doctrine.orm.entity_manager"
        calls:
            - [ 'setPositionField', ["%pix.sortable.behavior.position.field%"]]
            - [ 'setSortableGroups', ["%pix.sortable.behavior.sortable_groups%"]]
    Pix\SortableBehaviorBundle\Services\PositionORMHandler:
        alias: 'pix_sortable_behavior.position.orm'

    pix_sortable_behavior.position.mongodb:
        class: Pix\SortableBehaviorBundle\Services\PositionODMHandler
        public: false
        arguments:
            - "@doctrine_mongodb.odm.document_manager"
        calls:
            - [ 'setPositionField', ["%pix.sortable.behavior.position.field%"]]

    pix_sortable_behavior.twig.extension:
        class: Pix\SortableBehaviorBundle\Twig\ObjectPositionExtension
        arguments:
            - "@pix_sortable_behavior.position"
        public: false
        tags:
            - { name: twig.extension }

    Pix\SortableBehaviorBundle\Controller\SortableAdminController:
        tags:
            - { name: 'container.service_subscriber', id: 'pix_sortable_behavior.position' }
